syntax = "proto3";

package terraplane.v1;

option go_package = "github.com/xyzjace/terraplane/pkg/terraplane/v1;terraplanev1";

message TerraformEnvelope {
  string job_id = 1; // UUID of the job. Stable across all messages for a given job
  oneof payload {
    PlanCommand plan = 2;
    Ack ack = 3;
    PlanResult plan_result = 4;
    ApplyCommand apply = 5;
    ApplyResult apply_result = 6;
    UnlockCommand unlock = 7;
    UnlockResult unlock_result = 8;
  }
}
message PlanCommand {
  string repo = 1;
  int32 pr_number = 2;
  string commit_hash = 3;
  string plan_flags = 4;
  string stack_name = 5;
  string dir = 6;
}
message Ack {
  string message = 1;
}
message PlanResult {
  bool success = 1;
  string output = 2;
  string error = 3;
}
message ApplyCommand {
  string repo = 1;
  int32 pr_number = 2;
  string commit_hash = 3;
} 
message ApplyResult {
  bool success = 1;
  string output = 2;
  string error = 3;
}
message UnlockCommand {
  string repo = 1;
  int32 pr_number = 2;
}
message UnlockResult {
  bool success = 1;
  string output = 2;
  string error = 3;
}
