services:
  orchestrator:
    build: .
    image: terraplane
    command: ["orchestrator"]
    ports:
      - "8080:8080"
    environment:
      ORCHESTRATOR_LISTEN_ADDRESS: 0.0.0.0
      ORCHESTRATOR_LISTEN_PORT: "8080"
    env_file:
      - .env

  agent-dev:
    image: terraplane
    command: ["agent"]
    depends_on:
      - orchestrator
    env_file:
      - .env
    environment:
      AGENT_ID: "agent-dev"
      AGENT_ORCHESTRATOR_URL: "ws://orchestrator:8080/ws"
      
  agent-prod:
    image: terraplane
    command: ["agent"]
    depends_on:
      - orchestrator
    env_file:
      - .env
    environment:
      AGENT_ID: "agent-prod"      
      AGENT_ORCHESTRATOR_URL: "ws://orchestrator:8080/ws"
