// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go
//
// Generated by this command:
//
//	mockgen -source=manager.go -destination=mock_workspace/mock_manager.go -package=mock_workspace
//

// Package mock_workspace is a generated GoMock package.
package mock_workspace

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// FetchWorkspace mocks base method.
func (m *MockManager) FetchWorkspace(ctx context.Context, repo, revision, stack string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchWorkspace", ctx, repo, revision, stack)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchWorkspace indicates an expected call of FetchWorkspace.
func (mr *MockManagerMockRecorder) FetchWorkspace(ctx, repo, revision, stack any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchWorkspace", reflect.TypeOf((*MockManager)(nil).FetchWorkspace), ctx, repo, revision, stack)
}

// ProvisionWorkspace mocks base method.
func (m *MockManager) ProvisionWorkspace(ctx context.Context, repo, revision, stack string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProvisionWorkspace", ctx, repo, revision, stack)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProvisionWorkspace indicates an expected call of ProvisionWorkspace.
func (mr *MockManagerMockRecorder) ProvisionWorkspace(ctx, repo, revision, stack any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProvisionWorkspace", reflect.TypeOf((*MockManager)(nil).ProvisionWorkspace), ctx, repo, revision, stack)
}

// RemoveWorkspace mocks base method.
func (m *MockManager) RemoveWorkspace(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveWorkspace", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveWorkspace indicates an expected call of RemoveWorkspace.
func (mr *MockManagerMockRecorder) RemoveWorkspace(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWorkspace", reflect.TypeOf((*MockManager)(nil).RemoveWorkspace), ctx, path)
}
