// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: terraplane/v1/terraform_envelope.proto

package terraplanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TerraformEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // UUID of the job. Stable across all messages for a given job
	// Types that are valid to be assigned to Payload:
	//
	//	*TerraformEnvelope_Plan
	//	*TerraformEnvelope_Ack
	//	*TerraformEnvelope_PlanResult
	//	*TerraformEnvelope_Apply
	//	*TerraformEnvelope_ApplyResult
	//	*TerraformEnvelope_Unlock
	//	*TerraformEnvelope_UnlockResult
	Payload       isTerraformEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerraformEnvelope) Reset() {
	*x = TerraformEnvelope{}
	mi := &file_terraplane_v1_terraform_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerraformEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerraformEnvelope) ProtoMessage() {}

func (x *TerraformEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_terraplane_v1_terraform_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerraformEnvelope.ProtoReflect.Descriptor instead.
func (*TerraformEnvelope) Descriptor() ([]byte, []int) {
	return file_terraplane_v1_terraform_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *TerraformEnvelope) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TerraformEnvelope) GetPayload() isTerraformEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TerraformEnvelope) GetPlan() *PlanCommand {
	if x != nil {
		if x, ok := x.Payload.(*TerraformEnvelope_Plan); ok {
			return x.Plan
		}
	}
	return nil
}

func (x *TerraformEnvelope) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*TerraformEnvelope_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *TerraformEnvelope) GetPlanResult() *PlanResult {
	if x != nil {
		if x, ok := x.Payload.(*TerraformEnvelope_PlanResult); ok {
			return x.PlanResult
		}
	}
	return nil
}

func (x *TerraformEnvelope) GetApply() *ApplyCommand {
	if x != nil {
		if x, ok := x.Payload.(*TerraformEnvelope_Apply); ok {
			return x.Apply
		}
	}
	return nil
}

func (x *TerraformEnvelope) GetApplyResult() *ApplyResult {
	if x != nil {
		if x, ok := x.Payload.(*TerraformEnvelope_ApplyResult); ok {
			return x.ApplyResult
		}
	}
	return nil
}

func (x *TerraformEnvelope) GetUnlock() *UnlockCommand {
	if x != nil {
		if x, ok := x.Payload.(*TerraformEnvelope_Unlock); ok {
			return x.Unlock
		}
	}
	return nil
}

func (x *TerraformEnvelope) GetUnlockResult() *UnlockResult {
	if x != nil {
		if x, ok := x.Payload.(*TerraformEnvelope_UnlockResult); ok {
			return x.UnlockResult
		}
	}
	return nil
}

type isTerraformEnvelope_Payload interface {
	isTerraformEnvelope_Payload()
}

type TerraformEnvelope_Plan struct {
	Plan *PlanCommand `protobuf:"bytes,2,opt,name=plan,proto3,oneof"`
}

type TerraformEnvelope_Ack struct {
	Ack *Ack `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

type TerraformEnvelope_PlanResult struct {
	PlanResult *PlanResult `protobuf:"bytes,4,opt,name=plan_result,json=planResult,proto3,oneof"`
}

type TerraformEnvelope_Apply struct {
	Apply *ApplyCommand `protobuf:"bytes,5,opt,name=apply,proto3,oneof"`
}

type TerraformEnvelope_ApplyResult struct {
	ApplyResult *ApplyResult `protobuf:"bytes,6,opt,name=apply_result,json=applyResult,proto3,oneof"`
}

type TerraformEnvelope_Unlock struct {
	Unlock *UnlockCommand `protobuf:"bytes,7,opt,name=unlock,proto3,oneof"`
}

type TerraformEnvelope_UnlockResult struct {
	UnlockResult *UnlockResult `protobuf:"bytes,8,opt,name=unlock_result,json=unlockResult,proto3,oneof"`
}

func (*TerraformEnvelope_Plan) isTerraformEnvelope_Payload() {}

func (*TerraformEnvelope_Ack) isTerraformEnvelope_Payload() {}

func (*TerraformEnvelope_PlanResult) isTerraformEnvelope_Payload() {}

func (*TerraformEnvelope_Apply) isTerraformEnvelope_Payload() {}

func (*TerraformEnvelope_ApplyResult) isTerraformEnvelope_Payload() {}

func (*TerraformEnvelope_Unlock) isTerraformEnvelope_Payload() {}

func (*TerraformEnvelope_UnlockResult) isTerraformEnvelope_Payload() {}

type PlanCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	PrNumber      int32                  `protobuf:"varint,2,opt,name=pr_number,json=prNumber,proto3" json:"pr_number,omitempty"`
	CommitHash    string                 `protobuf:"bytes,3,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	PlanFlags     string                 `protobuf:"bytes,4,opt,name=plan_flags,json=planFlags,proto3" json:"plan_flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanCommand) Reset() {
	*x = PlanCommand{}
	mi := &file_terraplane_v1_terraform_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanCommand) ProtoMessage() {}

func (x *PlanCommand) ProtoReflect() protoreflect.Message {
	mi := &file_terraplane_v1_terraform_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanCommand.ProtoReflect.Descriptor instead.
func (*PlanCommand) Descriptor() ([]byte, []int) {
	return file_terraplane_v1_terraform_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *PlanCommand) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *PlanCommand) GetPrNumber() int32 {
	if x != nil {
		return x.PrNumber
	}
	return 0
}

func (x *PlanCommand) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *PlanCommand) GetPlanFlags() string {
	if x != nil {
		return x.PlanFlags
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_terraplane_v1_terraform_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_terraplane_v1_terraform_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_terraplane_v1_terraform_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PlanResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanResult) Reset() {
	*x = PlanResult{}
	mi := &file_terraplane_v1_terraform_envelope_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResult) ProtoMessage() {}

func (x *PlanResult) ProtoReflect() protoreflect.Message {
	mi := &file_terraplane_v1_terraform_envelope_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResult.ProtoReflect.Descriptor instead.
func (*PlanResult) Descriptor() ([]byte, []int) {
	return file_terraplane_v1_terraform_envelope_proto_rawDescGZIP(), []int{3}
}

func (x *PlanResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlanResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *PlanResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ApplyCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	PrNumber      int32                  `protobuf:"varint,2,opt,name=pr_number,json=prNumber,proto3" json:"pr_number,omitempty"`
	CommitHash    string                 `protobuf:"bytes,3,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	Branch        string                 `protobuf:"bytes,4,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyCommand) Reset() {
	*x = ApplyCommand{}
	mi := &file_terraplane_v1_terraform_envelope_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyCommand) ProtoMessage() {}

func (x *ApplyCommand) ProtoReflect() protoreflect.Message {
	mi := &file_terraplane_v1_terraform_envelope_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyCommand.ProtoReflect.Descriptor instead.
func (*ApplyCommand) Descriptor() ([]byte, []int) {
	return file_terraplane_v1_terraform_envelope_proto_rawDescGZIP(), []int{4}
}

func (x *ApplyCommand) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *ApplyCommand) GetPrNumber() int32 {
	if x != nil {
		return x.PrNumber
	}
	return 0
}

func (x *ApplyCommand) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *ApplyCommand) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type ApplyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResult) Reset() {
	*x = ApplyResult{}
	mi := &file_terraplane_v1_terraform_envelope_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResult) ProtoMessage() {}

func (x *ApplyResult) ProtoReflect() protoreflect.Message {
	mi := &file_terraplane_v1_terraform_envelope_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResult.ProtoReflect.Descriptor instead.
func (*ApplyResult) Descriptor() ([]byte, []int) {
	return file_terraplane_v1_terraform_envelope_proto_rawDescGZIP(), []int{5}
}

func (x *ApplyResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApplyResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ApplyResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UnlockCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	PrNumber      int32                  `protobuf:"varint,2,opt,name=pr_number,json=prNumber,proto3" json:"pr_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockCommand) Reset() {
	*x = UnlockCommand{}
	mi := &file_terraplane_v1_terraform_envelope_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockCommand) ProtoMessage() {}

func (x *UnlockCommand) ProtoReflect() protoreflect.Message {
	mi := &file_terraplane_v1_terraform_envelope_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockCommand.ProtoReflect.Descriptor instead.
func (*UnlockCommand) Descriptor() ([]byte, []int) {
	return file_terraplane_v1_terraform_envelope_proto_rawDescGZIP(), []int{6}
}

func (x *UnlockCommand) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *UnlockCommand) GetPrNumber() int32 {
	if x != nil {
		return x.PrNumber
	}
	return 0
}

type UnlockResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockResult) Reset() {
	*x = UnlockResult{}
	mi := &file_terraplane_v1_terraform_envelope_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockResult) ProtoMessage() {}

func (x *UnlockResult) ProtoReflect() protoreflect.Message {
	mi := &file_terraplane_v1_terraform_envelope_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockResult.ProtoReflect.Descriptor instead.
func (*UnlockResult) Descriptor() ([]byte, []int) {
	return file_terraplane_v1_terraform_envelope_proto_rawDescGZIP(), []int{7}
}

func (x *UnlockResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnlockResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *UnlockResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_terraplane_v1_terraform_envelope_proto protoreflect.FileDescriptor

const file_terraplane_v1_terraform_envelope_proto_rawDesc = "" +
	"\n" +
	"&terraplane/v1/terraform_envelope.proto\x12\rterraplane.v1\"\xbf\x03\n" +
	"\x11TerraformEnvelope\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x120\n" +
	"\x04plan\x18\x02 \x01(\v2\x1a.terraplane.v1.PlanCommandH\x00R\x04plan\x12&\n" +
	"\x03ack\x18\x03 \x01(\v2\x12.terraplane.v1.AckH\x00R\x03ack\x12<\n" +
	"\vplan_result\x18\x04 \x01(\v2\x19.terraplane.v1.PlanResultH\x00R\n" +
	"planResult\x123\n" +
	"\x05apply\x18\x05 \x01(\v2\x1b.terraplane.v1.ApplyCommandH\x00R\x05apply\x12?\n" +
	"\fapply_result\x18\x06 \x01(\v2\x1a.terraplane.v1.ApplyResultH\x00R\vapplyResult\x126\n" +
	"\x06unlock\x18\a \x01(\v2\x1c.terraplane.v1.UnlockCommandH\x00R\x06unlock\x12B\n" +
	"\runlock_result\x18\b \x01(\v2\x1b.terraplane.v1.UnlockResultH\x00R\funlockResultB\t\n" +
	"\apayload\"~\n" +
	"\vPlanCommand\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x1b\n" +
	"\tpr_number\x18\x02 \x01(\x05R\bprNumber\x12\x1f\n" +
	"\vcommit_hash\x18\x03 \x01(\tR\n" +
	"commitHash\x12\x1d\n" +
	"\n" +
	"plan_flags\x18\x04 \x01(\tR\tplanFlags\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"T\n" +
	"\n" +
	"PlanResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"x\n" +
	"\fApplyCommand\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x1b\n" +
	"\tpr_number\x18\x02 \x01(\x05R\bprNumber\x12\x1f\n" +
	"\vcommit_hash\x18\x03 \x01(\tR\n" +
	"commitHash\x12\x16\n" +
	"\x06branch\x18\x04 \x01(\tR\x06branch\"U\n" +
	"\vApplyResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"@\n" +
	"\rUnlockCommand\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x1b\n" +
	"\tpr_number\x18\x02 \x01(\x05R\bprNumber\"V\n" +
	"\fUnlockResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05errorB>Z<github.com/xyzjace/terraplane/pkg/terraplane/v1;terraplanev1b\x06proto3"

var (
	file_terraplane_v1_terraform_envelope_proto_rawDescOnce sync.Once
	file_terraplane_v1_terraform_envelope_proto_rawDescData []byte
)

func file_terraplane_v1_terraform_envelope_proto_rawDescGZIP() []byte {
	file_terraplane_v1_terraform_envelope_proto_rawDescOnce.Do(func() {
		file_terraplane_v1_terraform_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_terraplane_v1_terraform_envelope_proto_rawDesc), len(file_terraplane_v1_terraform_envelope_proto_rawDesc)))
	})
	return file_terraplane_v1_terraform_envelope_proto_rawDescData
}

var file_terraplane_v1_terraform_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_terraplane_v1_terraform_envelope_proto_goTypes = []any{
	(*TerraformEnvelope)(nil), // 0: terraplane.v1.TerraformEnvelope
	(*PlanCommand)(nil),       // 1: terraplane.v1.PlanCommand
	(*Ack)(nil),               // 2: terraplane.v1.Ack
	(*PlanResult)(nil),        // 3: terraplane.v1.PlanResult
	(*ApplyCommand)(nil),      // 4: terraplane.v1.ApplyCommand
	(*ApplyResult)(nil),       // 5: terraplane.v1.ApplyResult
	(*UnlockCommand)(nil),     // 6: terraplane.v1.UnlockCommand
	(*UnlockResult)(nil),      // 7: terraplane.v1.UnlockResult
}
var file_terraplane_v1_terraform_envelope_proto_depIdxs = []int32{
	1, // 0: terraplane.v1.TerraformEnvelope.plan:type_name -> terraplane.v1.PlanCommand
	2, // 1: terraplane.v1.TerraformEnvelope.ack:type_name -> terraplane.v1.Ack
	3, // 2: terraplane.v1.TerraformEnvelope.plan_result:type_name -> terraplane.v1.PlanResult
	4, // 3: terraplane.v1.TerraformEnvelope.apply:type_name -> terraplane.v1.ApplyCommand
	5, // 4: terraplane.v1.TerraformEnvelope.apply_result:type_name -> terraplane.v1.ApplyResult
	6, // 5: terraplane.v1.TerraformEnvelope.unlock:type_name -> terraplane.v1.UnlockCommand
	7, // 6: terraplane.v1.TerraformEnvelope.unlock_result:type_name -> terraplane.v1.UnlockResult
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_terraplane_v1_terraform_envelope_proto_init() }
func file_terraplane_v1_terraform_envelope_proto_init() {
	if File_terraplane_v1_terraform_envelope_proto != nil {
		return
	}
	file_terraplane_v1_terraform_envelope_proto_msgTypes[0].OneofWrappers = []any{
		(*TerraformEnvelope_Plan)(nil),
		(*TerraformEnvelope_Ack)(nil),
		(*TerraformEnvelope_PlanResult)(nil),
		(*TerraformEnvelope_Apply)(nil),
		(*TerraformEnvelope_ApplyResult)(nil),
		(*TerraformEnvelope_Unlock)(nil),
		(*TerraformEnvelope_UnlockResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_terraplane_v1_terraform_envelope_proto_rawDesc), len(file_terraplane_v1_terraform_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_terraplane_v1_terraform_envelope_proto_goTypes,
		DependencyIndexes: file_terraplane_v1_terraform_envelope_proto_depIdxs,
		MessageInfos:      file_terraplane_v1_terraform_envelope_proto_msgTypes,
	}.Build()
	File_terraplane_v1_terraform_envelope_proto = out.File
	file_terraplane_v1_terraform_envelope_proto_goTypes = nil
	file_terraplane_v1_terraform_envelope_proto_depIdxs = nil
}
