// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: terraplane/v1/websocket_envelope.proto

package terraplanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebsocketEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WebsocketEnvelope_Hello
	//	*WebsocketEnvelope_Goodbye
	Payload       isWebsocketEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketEnvelope) Reset() {
	*x = WebsocketEnvelope{}
	mi := &file_terraplane_v1_websocket_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketEnvelope) ProtoMessage() {}

func (x *WebsocketEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_terraplane_v1_websocket_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketEnvelope.ProtoReflect.Descriptor instead.
func (*WebsocketEnvelope) Descriptor() ([]byte, []int) {
	return file_terraplane_v1_websocket_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *WebsocketEnvelope) GetPayload() isWebsocketEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WebsocketEnvelope) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*WebsocketEnvelope_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WebsocketEnvelope) GetGoodbye() *Goodbye {
	if x != nil {
		if x, ok := x.Payload.(*WebsocketEnvelope_Goodbye); ok {
			return x.Goodbye
		}
	}
	return nil
}

type isWebsocketEnvelope_Payload interface {
	isWebsocketEnvelope_Payload()
}

type WebsocketEnvelope_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type WebsocketEnvelope_Goodbye struct {
	Goodbye *Goodbye `protobuf:"bytes,2,opt,name=goodbye,proto3,oneof"`
}

func (*WebsocketEnvelope_Hello) isWebsocketEnvelope_Payload() {}

func (*WebsocketEnvelope_Goodbye) isWebsocketEnvelope_Payload() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_terraplane_v1_websocket_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_terraplane_v1_websocket_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_terraplane_v1_websocket_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type Goodbye struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Goodbye) Reset() {
	*x = Goodbye{}
	mi := &file_terraplane_v1_websocket_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Goodbye) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goodbye) ProtoMessage() {}

func (x *Goodbye) ProtoReflect() protoreflect.Message {
	mi := &file_terraplane_v1_websocket_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goodbye.ProtoReflect.Descriptor instead.
func (*Goodbye) Descriptor() ([]byte, []int) {
	return file_terraplane_v1_websocket_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *Goodbye) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

var File_terraplane_v1_websocket_envelope_proto protoreflect.FileDescriptor

const file_terraplane_v1_websocket_envelope_proto_rawDesc = "" +
	"\n" +
	"&terraplane/v1/websocket_envelope.proto\x12\rterraplane.v1\"\x80\x01\n" +
	"\x11WebsocketEnvelope\x12,\n" +
	"\x05hello\x18\x01 \x01(\v2\x14.terraplane.v1.HelloH\x00R\x05hello\x122\n" +
	"\agoodbye\x18\x02 \x01(\v2\x16.terraplane.v1.GoodbyeH\x00R\agoodbyeB\t\n" +
	"\apayload\"\"\n" +
	"\x05Hello\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"$\n" +
	"\aGoodbye\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentIdB>Z<github.com/xyzjace/terraplane/pkg/terraplane/v1;terraplanev1b\x06proto3"

var (
	file_terraplane_v1_websocket_envelope_proto_rawDescOnce sync.Once
	file_terraplane_v1_websocket_envelope_proto_rawDescData []byte
)

func file_terraplane_v1_websocket_envelope_proto_rawDescGZIP() []byte {
	file_terraplane_v1_websocket_envelope_proto_rawDescOnce.Do(func() {
		file_terraplane_v1_websocket_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_terraplane_v1_websocket_envelope_proto_rawDesc), len(file_terraplane_v1_websocket_envelope_proto_rawDesc)))
	})
	return file_terraplane_v1_websocket_envelope_proto_rawDescData
}

var file_terraplane_v1_websocket_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_terraplane_v1_websocket_envelope_proto_goTypes = []any{
	(*WebsocketEnvelope)(nil), // 0: terraplane.v1.WebsocketEnvelope
	(*Hello)(nil),             // 1: terraplane.v1.Hello
	(*Goodbye)(nil),           // 2: terraplane.v1.Goodbye
}
var file_terraplane_v1_websocket_envelope_proto_depIdxs = []int32{
	1, // 0: terraplane.v1.WebsocketEnvelope.hello:type_name -> terraplane.v1.Hello
	2, // 1: terraplane.v1.WebsocketEnvelope.goodbye:type_name -> terraplane.v1.Goodbye
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_terraplane_v1_websocket_envelope_proto_init() }
func file_terraplane_v1_websocket_envelope_proto_init() {
	if File_terraplane_v1_websocket_envelope_proto != nil {
		return
	}
	file_terraplane_v1_websocket_envelope_proto_msgTypes[0].OneofWrappers = []any{
		(*WebsocketEnvelope_Hello)(nil),
		(*WebsocketEnvelope_Goodbye)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_terraplane_v1_websocket_envelope_proto_rawDesc), len(file_terraplane_v1_websocket_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_terraplane_v1_websocket_envelope_proto_goTypes,
		DependencyIndexes: file_terraplane_v1_websocket_envelope_proto_depIdxs,
		MessageInfos:      file_terraplane_v1_websocket_envelope_proto_msgTypes,
	}.Build()
	File_terraplane_v1_websocket_envelope_proto = out.File
	file_terraplane_v1_websocket_envelope_proto_goTypes = nil
	file_terraplane_v1_websocket_envelope_proto_depIdxs = nil
}
