// Code generated by MockGen. DO NOT EDIT.
// Source: publisher.go
//
// Generated by this command:
//
//	mockgen -source=publisher.go -destination=mock_scm/mock_publisher.go -package=mock_scm
//

// Package mock_scm is a generated GoMock package.
package mock_scm

import (
	context "context"
	reflect "reflect"

	scm "github.com/xyzjace/terraplane/pkg/scm"
	gomock "go.uber.org/mock/gomock"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
	isgomock struct{}
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// AcknowledgeComment mocks base method.
func (m *MockPublisher) AcknowledgeComment(ctx context.Context, repo string, prNumber, commentID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcknowledgeComment", ctx, repo, prNumber, commentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcknowledgeComment indicates an expected call of AcknowledgeComment.
func (mr *MockPublisherMockRecorder) AcknowledgeComment(ctx, repo, prNumber, commentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcknowledgeComment", reflect.TypeOf((*MockPublisher)(nil).AcknowledgeComment), ctx, repo, prNumber, commentID)
}

// AppendNote mocks base method.
func (m *MockPublisher) AppendNote(ctx context.Context, repo string, prNumber int, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendNote", ctx, repo, prNumber, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendNote indicates an expected call of AppendNote.
func (mr *MockPublisherMockRecorder) AppendNote(ctx, repo, prNumber, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendNote", reflect.TypeOf((*MockPublisher)(nil).AppendNote), ctx, repo, prNumber, body)
}

// Name mocks base method.
func (m *MockPublisher) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPublisherMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPublisher)(nil).Name))
}

// UpsertStatus mocks base method.
func (m *MockPublisher) UpsertStatus(ctx context.Context, key scm.StatusKey, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertStatus", ctx, key, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertStatus indicates an expected call of UpsertStatus.
func (mr *MockPublisherMockRecorder) UpsertStatus(ctx, key, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertStatus", reflect.TypeOf((*MockPublisher)(nil).UpsertStatus), ctx, key, body)
}
