// Code generated by MockGen. DO NOT EDIT.
// Source: publisher.go
//
// Generated by this command:
//
//	mockgen -source=publisher.go -destination=mock_scm/mock_publisher.go -package=mock_scm
//

// Package mock_scm is a generated GoMock package.
package mock_scm

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
	isgomock struct{}
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockPublisher) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPublisherMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPublisher)(nil).Name))
}

// WriteComment mocks base method.
func (m *MockPublisher) WriteComment(ctx context.Context, repo string, prNumber int, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteComment", ctx, repo, prNumber, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteComment indicates an expected call of WriteComment.
func (mr *MockPublisherMockRecorder) WriteComment(ctx, repo, prNumber, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteComment", reflect.TypeOf((*MockPublisher)(nil).WriteComment), ctx, repo, prNumber, body)
}
