// Code generated by MockGen. DO NOT EDIT.
// Source: provider.go
//
// Generated by this command:
//
//	mockgen -source=provider.go -destination=mock_scm/mock_provider.go -package=mock_scm
//

// Package mock_scm is a generated GoMock package.
package mock_scm

import (
	http "net/http"
	reflect "reflect"

	scm "github.com/xyzjace/terraplane/pkg/scm"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// GetFile mocks base method.
func (m *MockProvider) GetFile(fileName, revision, repo string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", fileName, revision, repo)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockProviderMockRecorder) GetFile(fileName, revision, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockProvider)(nil).GetFile), fileName, revision, repo)
}

// Name mocks base method.
func (m *MockProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockProvider)(nil).Name))
}

// ParseWebhook mocks base method.
func (m *MockProvider) ParseWebhook(r *http.Request) ([]scm.Webhook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseWebhook", r)
	ret0, _ := ret[0].([]scm.Webhook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseWebhook indicates an expected call of ParseWebhook.
func (mr *MockProviderMockRecorder) ParseWebhook(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseWebhook", reflect.TypeOf((*MockProvider)(nil).ParseWebhook), r)
}
