// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xyzjace/terraplane/pkg/agent (interfaces: Dispatcher)
//
// Generated by this command:
//
//	mockgen -destination=mock_agent/mock_dispatcher.go -package=mock_agent github.com/xyzjace/terraplane/pkg/agent Dispatcher
//

// Package mock_agent is a generated GoMock package.
package mock_agent

import (
	context "context"
	reflect "reflect"

	command "github.com/xyzjace/terraplane/pkg/command"
	gomock "go.uber.org/mock/gomock"
)

// MockDispatcher is a mock of Dispatcher interface.
type MockDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockDispatcherMockRecorder
	isgomock struct{}
}

// MockDispatcherMockRecorder is the mock recorder for MockDispatcher.
type MockDispatcherMockRecorder struct {
	mock *MockDispatcher
}

// NewMockDispatcher creates a new mock instance.
func NewMockDispatcher(ctrl *gomock.Controller) *MockDispatcher {
	mock := &MockDispatcher{ctrl: ctrl}
	mock.recorder = &MockDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDispatcher) EXPECT() *MockDispatcherMockRecorder {
	return m.recorder
}

// Dispatch mocks base method.
func (m *MockDispatcher) Dispatch(ctx context.Context, cmd *command.Command, done chan<- struct{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Dispatch", ctx, cmd, done)
}

// Dispatch indicates an expected call of Dispatch.
func (mr *MockDispatcherMockRecorder) Dispatch(ctx, cmd, done any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dispatch", reflect.TypeOf((*MockDispatcher)(nil).Dispatch), ctx, cmd, done)
}
