// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_github/mock_client.go -package=mock_github
//

// Package mock_github is a generated GoMock package.
package mock_github

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetCommitSHA mocks base method.
func (m *MockClient) GetCommitSHA(ctx context.Context, repo string, prNumber int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitSHA", ctx, repo, prNumber)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitSHA indicates an expected call of GetCommitSHA.
func (mr *MockClientMockRecorder) GetCommitSHA(ctx, repo, prNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitSHA", reflect.TypeOf((*MockClient)(nil).GetCommitSHA), ctx, repo, prNumber)
}

// GetFile mocks base method.
func (m *MockClient) GetFile(ctx context.Context, repo, path, revision string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", ctx, repo, path, revision)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockClientMockRecorder) GetFile(ctx, repo, path, revision any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockClient)(nil).GetFile), ctx, repo, path, revision)
}

// WriteComment mocks base method.
func (m *MockClient) WriteComment(ctx context.Context, repo string, prNumber int, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteComment", ctx, repo, prNumber, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteComment indicates an expected call of WriteComment.
func (mr *MockClientMockRecorder) WriteComment(ctx, repo, prNumber, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteComment", reflect.TypeOf((*MockClient)(nil).WriteComment), ctx, repo, prNumber, body)
}
