// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/goforj/wire"
	"github.com/xyzjace/terraplane/config"
	"github.com/xyzjace/terraplane/internal/logging"
	"github.com/xyzjace/terraplane/pkg/agent"
	"github.com/xyzjace/terraplane/pkg/agentsession"
	"github.com/xyzjace/terraplane/pkg/orchestrator"
	"github.com/xyzjace/terraplane/pkg/orchestrator/services"
	"github.com/xyzjace/terraplane/pkg/scm/github"
	"github.com/xyzjace/terraplane/pkg/storage"
	"github.com/xyzjace/terraplane/pkg/webserver"
)

// Injectors from wire.go:

func InitializeOrchestrator() (orchestrator.Manager, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	logger := logging.NewLogger(configConfig)
	client := github.NewClient(configConfig)
	provider := github.NewProvider(logger, configConfig, client)
	registry := agentsession.NewRegistry(logger)
	db, err := storage.New(configConfig)
	if err != nil {
		return nil, err
	}
	jobRepository := storage.NewJobRepository(db)
	lockRepository := storage.NewLockRepository(db)
	factory := agentsession.NewFactory(logger, registry, jobRepository, lockRepository)
	planService := services.NewPlanService(logger, registry, provider, jobRepository, lockRepository)
	applyService := services.NewApplyService(logger, registry, provider, jobRepository)
	unlockService := services.NewUnlockService(logger, registry, provider, jobRepository, lockRepository)
	handler := webserver.NewHandler(logger, provider, registry, factory, planService, applyService, unlockService)
	server := webserver.NewServer(configConfig, logger, handler)
	manager := orchestrator.NewManager(configConfig, logger, server, db)
	return manager, nil
}

func InitializeAgent() (agent.Manager, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	logger := logging.NewLogger(configConfig)
	manager := agent.NewManager(configConfig, logger)
	return manager, nil
}

// wire.go:

var observableSet = wire.NewSet(logging.NewLogger)
