// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/goforj/wire"
	"github.com/xyzjace/terraplane/internal/logging"
	"github.com/xyzjace/terraplane/pkg/orchestrator"
)

// Injectors from wire.go:

func InitializeOrchestrator() (orchestrator.Orchestrator, error) {
	logger := logging.NewLogger()
	orchestratorOrchestrator := orchestrator.NewOrchestrator(logger)
	return orchestratorOrchestrator, nil
}

// wire.go:

var observableSet = wire.NewSet(logging.NewLogger)
