// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/goforj/wire"
	"github.com/xyzjace/terraplane/config"
	"github.com/xyzjace/terraplane/internal/logging"
	"github.com/xyzjace/terraplane/pkg/agent"
	orchestrator2 "github.com/xyzjace/terraplane/pkg/agent/orchestrator"
	"github.com/xyzjace/terraplane/pkg/agent/terraform"
	"github.com/xyzjace/terraplane/pkg/agent/workspace"
	"github.com/xyzjace/terraplane/pkg/orchestrator"
	"github.com/xyzjace/terraplane/pkg/orchestrator/services"
	"github.com/xyzjace/terraplane/pkg/scm/factory"
	"github.com/xyzjace/terraplane/pkg/storage"
	"github.com/xyzjace/terraplane/pkg/webserver"
)

// Injectors from wire.go:

func InitializeOrchestrator() (orchestrator.Manager, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	logger := logging.NewLogger(configConfig)
	provider, err := factory.NewProvider(logger, configConfig)
	if err != nil {
		return nil, err
	}
	publisher, err := factory.NewPublisher(logger, configConfig)
	if err != nil {
		return nil, err
	}
	db, err := storage.New(configConfig)
	if err != nil {
		return nil, err
	}
	jobRepository := storage.NewJobRepository(db)
	lockRepository := storage.NewLockRepository(db)
	jobService := services.NewJobService(logger, jobRepository, lockRepository, provider, publisher, configConfig)
	handler := webserver.NewHandler(logger, provider, publisher, jobService, configConfig)
	server := webserver.NewServer(configConfig, logger, handler)
	dispatcher := orchestrator.NewDispatcher(configConfig, logger, jobService)
	manager := orchestrator.NewManager(configConfig, logger, server, db, dispatcher)
	return manager, nil
}

func InitializeAgent() (agent.Manager, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	logger := logging.NewLogger(configConfig)
	manager := workspace.NewManager(configConfig, logger)
	terraformManager := terraform.NewManager(configConfig, logger)
	client := orchestrator2.NewClient(configConfig)
	agentManager := agent.NewManager(configConfig, logger, manager, terraformManager, client)
	return agentManager, nil
}

// wire.go:

var observableSet = wire.NewSet(logging.NewLogger)
