// Code generated by MockGen. DO NOT EDIT.
// Source: lock_repository.go
//
// Generated by this command:
//
//	mockgen -source=lock_repository.go -destination=mock_repository/mock_lock_repository.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	models "github.com/xyzjace/terraplane/pkg/storage/models"
	gomock "go.uber.org/mock/gomock"
)

// MockLockRepository is a mock of LockRepository interface.
type MockLockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLockRepositoryMockRecorder
	isgomock struct{}
}

// MockLockRepositoryMockRecorder is the mock recorder for MockLockRepository.
type MockLockRepositoryMockRecorder struct {
	mock *MockLockRepository
}

// NewMockLockRepository creates a new mock instance.
func NewMockLockRepository(ctrl *gomock.Controller) *MockLockRepository {
	mock := &MockLockRepository{ctrl: ctrl}
	mock.recorder = &MockLockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLockRepository) EXPECT() *MockLockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLockRepository) Create(ctx context.Context, lock *models.ProjectLock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, lock)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLockRepositoryMockRecorder) Create(ctx, lock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLockRepository)(nil).Create), ctx, lock)
}

// Delete mocks base method.
func (m *MockLockRepository) Delete(ctx context.Context, repo, stackName, workspace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, repo, stackName, workspace)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLockRepositoryMockRecorder) Delete(ctx, repo, stackName, workspace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLockRepository)(nil).Delete), ctx, repo, stackName, workspace)
}

// DeleteByRepoAndStacks mocks base method.
func (m *MockLockRepository) DeleteByRepoAndStacks(ctx context.Context, repo string, stackNames []string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByRepoAndStacks", ctx, repo, stackNames)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByRepoAndStacks indicates an expected call of DeleteByRepoAndStacks.
func (mr *MockLockRepositoryMockRecorder) DeleteByRepoAndStacks(ctx, repo, stackNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByRepoAndStacks", reflect.TypeOf((*MockLockRepository)(nil).DeleteByRepoAndStacks), ctx, repo, stackNames)
}

// Get mocks base method.
func (m *MockLockRepository) Get(ctx context.Context, repo, stackName, workspace string) (*models.ProjectLock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, repo, stackName, workspace)
	ret0, _ := ret[0].(*models.ProjectLock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLockRepositoryMockRecorder) Get(ctx, repo, stackName, workspace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLockRepository)(nil).Get), ctx, repo, stackName, workspace)
}
