// Code generated by MockGen. DO NOT EDIT.
// Source: job_repository.go
//
// Generated by this command:
//
//	mockgen -source=job_repository.go -destination=mock_repository/mock_job_repository.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	models "github.com/xyzjace/terraplane/pkg/storage/models"
	gomock "go.uber.org/mock/gomock"
)

// MockJobRepository is a mock of JobRepository interface.
type MockJobRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobRepositoryMockRecorder
	isgomock struct{}
}

// MockJobRepositoryMockRecorder is the mock recorder for MockJobRepository.
type MockJobRepositoryMockRecorder struct {
	mock *MockJobRepository
}

// NewMockJobRepository creates a new mock instance.
func NewMockJobRepository(ctrl *gomock.Controller) *MockJobRepository {
	mock := &MockJobRepository{ctrl: ctrl}
	mock.recorder = &MockJobRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobRepository) EXPECT() *MockJobRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockJobRepository) Create(ctx context.Context, job *models.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockJobRepositoryMockRecorder) Create(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockJobRepository)(nil).Create), ctx, job)
}

// Delete mocks base method.
func (m *MockJobRepository) Delete(ctx context.Context, jobID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockJobRepositoryMockRecorder) Delete(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockJobRepository)(nil).Delete), ctx, jobID)
}

// DeleteByRepoPRAndStacks mocks base method.
func (m *MockJobRepository) DeleteByRepoPRAndStacks(ctx context.Context, repo string, prNumber int, stackNames []string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByRepoPRAndStacks", ctx, repo, prNumber, stackNames)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByRepoPRAndStacks indicates an expected call of DeleteByRepoPRAndStacks.
func (mr *MockJobRepositoryMockRecorder) DeleteByRepoPRAndStacks(ctx, repo, prNumber, stackNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByRepoPRAndStacks", reflect.TypeOf((*MockJobRepository)(nil).DeleteByRepoPRAndStacks), ctx, repo, prNumber, stackNames)
}

// Get mocks base method.
func (m *MockJobRepository) Get(ctx context.Context, jobID string) (*models.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, jobID)
	ret0, _ := ret[0].(*models.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockJobRepositoryMockRecorder) Get(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockJobRepository)(nil).Get), ctx, jobID)
}

// GetPendingJob mocks base method.
func (m *MockJobRepository) GetPendingJob(ctx context.Context, repo string, prNumber int, stackName, action string) (*models.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingJob", ctx, repo, prNumber, stackName, action)
	ret0, _ := ret[0].(*models.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingJob indicates an expected call of GetPendingJob.
func (mr *MockJobRepositoryMockRecorder) GetPendingJob(ctx, repo, prNumber, stackName, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingJob", reflect.TypeOf((*MockJobRepository)(nil).GetPendingJob), ctx, repo, prNumber, stackName, action)
}

// Update mocks base method.
func (m *MockJobRepository) Update(ctx context.Context, job *models.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockJobRepositoryMockRecorder) Update(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockJobRepository)(nil).Update), ctx, job)
}

// UpsertPendingJob mocks base method.
func (m *MockJobRepository) UpsertPendingJob(ctx context.Context, repo string, prNumber int, stackName, action string, payload map[string]any, agent string) (*models.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPendingJob", ctx, repo, prNumber, stackName, action, payload, agent)
	ret0, _ := ret[0].(*models.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertPendingJob indicates an expected call of UpsertPendingJob.
func (mr *MockJobRepositoryMockRecorder) UpsertPendingJob(ctx, repo, prNumber, stackName, action, payload, agent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPendingJob", reflect.TypeOf((*MockJobRepository)(nil).UpsertPendingJob), ctx, repo, prNumber, stackName, action, payload, agent)
}
