// Code generated by MockGen. DO NOT EDIT.
// Source: job_repository.go
//
// Generated by this command:
//
//	mockgen -source=job_repository.go -destination=mock_repository/mock_job_repository.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/xyzjace/terraplane/pkg/storage/models"
	gomock "go.uber.org/mock/gomock"
)

// MockJobRepository is a mock of JobRepository interface.
type MockJobRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobRepositoryMockRecorder
	isgomock struct{}
}

// MockJobRepositoryMockRecorder is the mock recorder for MockJobRepository.
type MockJobRepositoryMockRecorder struct {
	mock *MockJobRepository
}

// NewMockJobRepository creates a new mock instance.
func NewMockJobRepository(ctrl *gomock.Controller) *MockJobRepository {
	mock := &MockJobRepository{ctrl: ctrl}
	mock.recorder = &MockJobRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobRepository) EXPECT() *MockJobRepositoryMockRecorder {
	return m.recorder
}

// ClaimPendingJobForAgent mocks base method.
func (m *MockJobRepository) ClaimPendingJobForAgent(ctx context.Context, agentID string, status models.JobStatus, leaseExpiresAt *time.Time) (*models.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimPendingJobForAgent", ctx, agentID, status, leaseExpiresAt)
	ret0, _ := ret[0].(*models.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimPendingJobForAgent indicates an expected call of ClaimPendingJobForAgent.
func (mr *MockJobRepositoryMockRecorder) ClaimPendingJobForAgent(ctx, agentID, status, leaseExpiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimPendingJobForAgent", reflect.TypeOf((*MockJobRepository)(nil).ClaimPendingJobForAgent), ctx, agentID, status, leaseExpiresAt)
}

// Create mocks base method.
func (m *MockJobRepository) Create(ctx context.Context, job *models.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockJobRepositoryMockRecorder) Create(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockJobRepository)(nil).Create), ctx, job)
}

// Delete mocks base method.
func (m *MockJobRepository) Delete(ctx context.Context, jobID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockJobRepositoryMockRecorder) Delete(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockJobRepository)(nil).Delete), ctx, jobID)
}

// DeleteByRepoPRAndStacks mocks base method.
func (m *MockJobRepository) DeleteByRepoPRAndStacks(ctx context.Context, repo string, prNumber int, stackNames []string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByRepoPRAndStacks", ctx, repo, prNumber, stackNames)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByRepoPRAndStacks indicates an expected call of DeleteByRepoPRAndStacks.
func (mr *MockJobRepositoryMockRecorder) DeleteByRepoPRAndStacks(ctx, repo, prNumber, stackNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByRepoPRAndStacks", reflect.TypeOf((*MockJobRepository)(nil).DeleteByRepoPRAndStacks), ctx, repo, prNumber, stackNames)
}

// FailClaimedJob mocks base method.
func (m *MockJobRepository) FailClaimedJob(ctx context.Context, jobID, errMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailClaimedJob", ctx, jobID, errMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailClaimedJob indicates an expected call of FailClaimedJob.
func (mr *MockJobRepositoryMockRecorder) FailClaimedJob(ctx, jobID, errMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailClaimedJob", reflect.TypeOf((*MockJobRepository)(nil).FailClaimedJob), ctx, jobID, errMsg)
}

// Get mocks base method.
func (m *MockJobRepository) Get(ctx context.Context, jobID string) (*models.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, jobID)
	ret0, _ := ret[0].(*models.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockJobRepositoryMockRecorder) Get(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockJobRepository)(nil).Get), ctx, jobID)
}

// ReapExpiredClaims mocks base method.
func (m *MockJobRepository) ReapExpiredClaims(ctx context.Context, now time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReapExpiredClaims", ctx, now)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReapExpiredClaims indicates an expected call of ReapExpiredClaims.
func (mr *MockJobRepositoryMockRecorder) ReapExpiredClaims(ctx, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReapExpiredClaims", reflect.TypeOf((*MockJobRepository)(nil).ReapExpiredClaims), ctx, now)
}

// RefreshAgentClaims mocks base method.
func (m *MockJobRepository) RefreshAgentClaims(ctx context.Context, agentID string, leaseExpiresAt *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshAgentClaims", ctx, agentID, leaseExpiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshAgentClaims indicates an expected call of RefreshAgentClaims.
func (mr *MockJobRepositoryMockRecorder) RefreshAgentClaims(ctx, agentID, leaseExpiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshAgentClaims", reflect.TypeOf((*MockJobRepository)(nil).RefreshAgentClaims), ctx, agentID, leaseExpiresAt)
}

// ReleaseClaimedJob mocks base method.
func (m *MockJobRepository) ReleaseClaimedJob(ctx context.Context, jobID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseClaimedJob", ctx, jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseClaimedJob indicates an expected call of ReleaseClaimedJob.
func (mr *MockJobRepositoryMockRecorder) ReleaseClaimedJob(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseClaimedJob", reflect.TypeOf((*MockJobRepository)(nil).ReleaseClaimedJob), ctx, jobID)
}

// Update mocks base method.
func (m *MockJobRepository) Update(ctx context.Context, job *models.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockJobRepositoryMockRecorder) Update(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockJobRepository)(nil).Update), ctx, job)
}

// UpsertPendingJob mocks base method.
func (m *MockJobRepository) UpsertPendingJob(ctx context.Context, repo string, prNumber int, stackName, action string, payload map[string]any, agent string) (*models.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPendingJob", ctx, repo, prNumber, stackName, action, payload, agent)
	ret0, _ := ret[0].(*models.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertPendingJob indicates an expected call of UpsertPendingJob.
func (mr *MockJobRepositoryMockRecorder) UpsertPendingJob(ctx, repo, prNumber, stackName, action, payload, agent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPendingJob", reflect.TypeOf((*MockJobRepository)(nil).UpsertPendingJob), ctx, repo, prNumber, stackName, action, payload, agent)
}
