// Code generated by MockGen. DO NOT EDIT.
// Source: runner.go
//
// Generated by this command:
//
//	mockgen -source=runner.go -destination=mock_terraform/mock_runner.go -package=mock_terraform
//

// Package mock_terraform is a generated GoMock package.
package mock_terraform

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRunner is a mock of Runner interface.
type MockRunner struct {
	ctrl     *gomock.Controller
	recorder *MockRunnerMockRecorder
	isgomock struct{}
}

// MockRunnerMockRecorder is the mock recorder for MockRunner.
type MockRunnerMockRecorder struct {
	mock *MockRunner
}

// NewMockRunner creates a new mock instance.
func NewMockRunner(ctrl *gomock.Controller) *MockRunner {
	mock := &MockRunner{ctrl: ctrl}
	mock.recorder = &MockRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunner) EXPECT() *MockRunnerMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockRunner) Apply(ctx context.Context, terraformBin, workDir string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", ctx, terraformBin, workDir)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Apply indicates an expected call of Apply.
func (mr *MockRunnerMockRecorder) Apply(ctx, terraformBin, workDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockRunner)(nil).Apply), ctx, terraformBin, workDir)
}

// Init mocks base method.
func (m *MockRunner) Init(ctx context.Context, terraformBin, workDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", ctx, terraformBin, workDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockRunnerMockRecorder) Init(ctx, terraformBin, workDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockRunner)(nil).Init), ctx, terraformBin, workDir)
}

// Plan mocks base method.
func (m *MockRunner) Plan(ctx context.Context, terraformBin, workDir, planFlags string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Plan", ctx, terraformBin, workDir, planFlags)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Plan indicates an expected call of Plan.
func (mr *MockRunnerMockRecorder) Plan(ctx, terraformBin, workDir, planFlags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Plan", reflect.TypeOf((*MockRunner)(nil).Plan), ctx, terraformBin, workDir, planFlags)
}
