// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go
//
// Generated by this command:
//
//	mockgen -source=manager.go -destination=mock_terraform/mock_manager.go -package=mock_terraform
//

// Package mock_terraform is a generated GoMock package.
package mock_terraform

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// RunApply mocks base method.
func (m *MockManager) RunApply(ctx context.Context, workspaceDir, stackName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunApply", ctx, workspaceDir, stackName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunApply indicates an expected call of RunApply.
func (mr *MockManagerMockRecorder) RunApply(ctx, workspaceDir, stackName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunApply", reflect.TypeOf((*MockManager)(nil).RunApply), ctx, workspaceDir, stackName)
}

// RunPlan mocks base method.
func (m *MockManager) RunPlan(ctx context.Context, workspaceDir, stackName, planFlags string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunPlan", ctx, workspaceDir, stackName, planFlags)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunPlan indicates an expected call of RunPlan.
func (mr *MockManagerMockRecorder) RunPlan(ctx, workspaceDir, stackName, planFlags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunPlan", reflect.TypeOf((*MockManager)(nil).RunPlan), ctx, workspaceDir, stackName, planFlags)
}
