// Code generated by MockGen. DO NOT EDIT.
// Source: version_manager.go
//
// Generated by this command:
//
//	mockgen -source=version_manager.go -destination=mock_terraform/mock_version_manager.go -package=mock_terraform
//

// Package mock_terraform is a generated GoMock package.
package mock_terraform

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVersionManager is a mock of VersionManager interface.
type MockVersionManager struct {
	ctrl     *gomock.Controller
	recorder *MockVersionManagerMockRecorder
	isgomock struct{}
}

// MockVersionManagerMockRecorder is the mock recorder for MockVersionManager.
type MockVersionManagerMockRecorder struct {
	mock *MockVersionManager
}

// NewMockVersionManager creates a new mock instance.
func NewMockVersionManager(ctrl *gomock.Controller) *MockVersionManager {
	mock := &MockVersionManager{ctrl: ctrl}
	mock.recorder = &MockVersionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVersionManager) EXPECT() *MockVersionManagerMockRecorder {
	return m.recorder
}

// Ensure mocks base method.
func (m *MockVersionManager) Ensure(ctx context.Context, version string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ensure", ctx, version)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ensure indicates an expected call of Ensure.
func (mr *MockVersionManagerMockRecorder) Ensure(ctx, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ensure", reflect.TypeOf((*MockVersionManager)(nil).Ensure), ctx, version)
}
