// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xyzjace/terraplane/pkg/agent/orchestrator (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination=mock_orchestrator/mock_client.go -package=mock_orchestrator github.com/xyzjace/terraplane/pkg/agent/orchestrator Client
//

// Package mock_orchestrator is a generated GoMock package.
package mock_orchestrator

import (
	context "context"
	reflect "reflect"

	command "github.com/xyzjace/terraplane/pkg/command"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Ack mocks base method.
func (m *MockClient) Ack(ctx context.Context, jobID, agentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ack", ctx, jobID, agentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ack indicates an expected call of Ack.
func (mr *MockClientMockRecorder) Ack(ctx, jobID, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ack", reflect.TypeOf((*MockClient)(nil).Ack), ctx, jobID, agentID)
}

// ClaimJob mocks base method.
func (m *MockClient) ClaimJob(ctx context.Context, agentID string) (*command.Command, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimJob", ctx, agentID)
	ret0, _ := ret[0].(*command.Command)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimJob indicates an expected call of ClaimJob.
func (mr *MockClientMockRecorder) ClaimJob(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimJob", reflect.TypeOf((*MockClient)(nil).ClaimJob), ctx, agentID)
}

// Heartbeat mocks base method.
func (m *MockClient) Heartbeat(ctx context.Context, jobID, agentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Heartbeat", ctx, jobID, agentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Heartbeat indicates an expected call of Heartbeat.
func (mr *MockClientMockRecorder) Heartbeat(ctx, jobID, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Heartbeat", reflect.TypeOf((*MockClient)(nil).Heartbeat), ctx, jobID, agentID)
}

// SubmitResult mocks base method.
func (m *MockClient) SubmitResult(ctx context.Context, jobID, agentID string, success bool, output, errMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitResult", ctx, jobID, agentID, success, output, errMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitResult indicates an expected call of SubmitResult.
func (mr *MockClientMockRecorder) SubmitResult(ctx, jobID, agentID, success, output, errMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitResult", reflect.TypeOf((*MockClient)(nil).SubmitResult), ctx, jobID, agentID, success, output, errMsg)
}
